### ISSUE TITLE
Liz Error

### ISSUE THREAD

**Issue by espencer14** [openjusticeok/ojo-markdown-factsheet-template#4]
tlmgr.pl: package log updated: C:/Users/eliza/AppData/Roaming/TinyTeX/texmf-var/web2c/tlmgr.log
! Package pdftex.def Error: File `design/OJO-Logo-White.png' not found: using d
raft setting.

Error: LaTeX failed to compile tw-evictions-template.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips. See tw-evictions-template.log for more info.
Execution halted

**Comment by brancengregory** [comment]
I have looked into this but can't replicate the issue. My suggestion would be to reinstall the ojodb package again using `devtools::install_github('openjusticeok/ojodb', force = T)` to see if the problem persists. If so then I believe the issue would be with tinytex. You can try reinstalling that. Otherwise, we will need to have a digital session to debug your R configuration
